# .github/workflows/douban.yml
name: douban

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  workflow_dispatch:

#on:
#  schedule:
#  - cron: "0 0 * * *"
#  watch:
#    types: [started]
permissions:
  actions: write
  checks:  write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
        
jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: backup data files
      run: |
        mv ./static/data/book.json ./static/data/douban/book_$(date +%Y-%m-%d).json.bak
        mv ./static/data/music.json ./static/data/douban/music_$(date +%Y-%m-%d).json.bak
        mv ./static/data/movie.json ./static/data/douban/movie_$(date +%Y-%m-%d).json.bak
    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: olikuio
        type: book
        format: json
        dir: ./static/data

    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: olikuio
        type: movie
        format: json
        dir: ./static/data
    - name: music
      uses: lizheming/doumark-action@master
      with:
        id: olikuio
        type: music
        format: json
        dir: ./static/data

    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        message: 'chore: update douban data'
        add: './static/data'