# .github/workflows/douban.yml
name: syncOpen

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  workflow_dispatch:

#on:
#  schedule:
#  - cron: "0 0 * * *"
#  watch:
#    types: [started]
permissions:
  actions: write
  checks:  write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
        
jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: olikuio
        type: book
        format: notion
        dir: 509f8da447f5425ca59f2ee28d46bc31
        notion_token: ${{ secrets.douban }}
    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: olikuio
        type: movie
        format: notion
        dir: 60ef9d3faef74050bdf0e337579081f9
        notion_token: ${{ secrets.douban }}
    - name: music
      uses: lizheming/doumark-action@master
      with:
        id: olikuio
        type: music
        format: notion
        dir: 1f7d1d30b7934ae6aa03b98c0a50699d
        notion_token: ${{ secrets.douban }}   
